### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by vxfung** [atomistic-machine-learning/cG-SchNet#1]
Hi,

I am wondering if it is possible to to have an option to use a custom dataset like in G-Schnet with a separate template class.

Thanks,
Victor

**Comment by NiklasGebauer** [comment]
Hi Victor,
unfortunately I did not adapt the template class from G-SchNet yet and I currently do not have the time to do it.
The code in this repository is mainly for reproducibility of the paper results on QM9.

Depending on your data, it might be possible for you to reuse `qm9_data.py` or adapt it yourself (especially if your data contains the same atom types as QM9).

I recently re-implemented cG-SchNet in the most recent version of schnetpack (the one from the dev-branch). I am currently testing that implementation. Hopefully, I will be able to release it soon. I think it is easier to configure and more modular, such that it should be easier to use custom data sets. If you have some time, it might be more convenient to wait for the release and then work with the new version.

Best,
Niklas
